In [ ]:
# Whas is MLP?
# -> Multi Layer Perceptron.
# Can you Draw it?
# ->

import torch 
import torch.nn as nn

# Some basic stuff you need to setup every time.
def _init_setup():
    torch.manual_seed(1477741)
    print("good luck 🍀")
_init_setup()


class my_mlp(nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = nn.Sequential(
            
            # hideen layer[0]
            nn.Linear(num_inputs, 3),
            nn.ReLU(),
            
            # hidden layer[1]
            nn.Linear(3, 6),
            nn.ReLU(),
            
            # output layer[]
            nn.Linear(6, num_outputs)
        )
    
    def forward(self, x):
        logits = self.layers[0](x)
        return logits
    
    def print_f(self, x):
        logits = self.layers[0](x)
        return logits
  
model = my_mlp(5, 3)

good luck 🍀


In [9]:
x = torch.tensor([0.2, 0.2, 0.2, 0.2, 0.2])

num_inputs = 5
num_outputs = 3
layers = nn.Sequential(
    
    # hideen layer[0]
    nn.Linear(num_inputs, 3),
    nn.ReLU(),
    
    # hidden layer[1]
    nn.Linear(3, 6),
    nn.ReLU(),
    
    # output layer[]
    nn.Linear(6, num_outputs)
)

layers[0](x)

tensor([ 0.2570,  0.4800, -0.0826], grad_fn=<ViewBackward0>)

In [12]:
x = torch.tensor([0.2, 0.2, 0.2, 0.2, 0.2])

num_inputs = 5
num_outputs = 3
layers = nn.Sequential(
    
    # hideen layer[0]
    nn.Linear(num_inputs, 3),
    
    # hidden layer[1]
    nn.Linear(3, 6),
    
    # output layer[]
    nn.Linear(6, num_outputs)
)

layers[0](x)

tensor([ 0.0317, -0.2882,  0.3947], grad_fn=<ViewBackward0>)

In [8]:
model

my_mlp(
  (layers): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=6, bias=True)
    (3): ReLU()
    (4): Linear(in_features=6, out_features=3, bias=True)
  )
)

In [3]:
model.layers[4].weight

Parameter containing:
tensor([[-0.1209,  0.1351,  0.1221,  0.1027, -0.0475,  0.2664],
        [ 0.2330, -0.1021, -0.3709, -0.3705, -0.0308, -0.1215],
        [ 0.2590, -0.3512, -0.2491,  0.2475,  0.1439, -0.2173]],
       requires_grad=True)

In [4]:
# our inputs
x = torch.tensor([0.1, 0.1, 0.1, 0.1, 0.1,])
# full forward will give use 3 out values.
model.print_f(x)

tensor([-0.0695,  0.4918,  0.1604], grad_fn=<ViewBackward0>)

In [5]:
ef = examples_features = torch.tensor([0.1, 0.1, 0.1, 0.1, 0.1,])
mL1 = model_weights_0L = model.layers[0].weight
wL1 = model.layers[0].bias
out_linear = ef @ mL1.T + wL1
print(out_linear) # -> Formula inside the model is (x @ w.T + b)
ra = torch.relu(out_linear)
print(ra)

tensor([-0.0695,  0.4918,  0.1604], grad_fn=<AddBackward0>)
tensor([0.0000, 0.4918, 0.1604], grad_fn=<ReluBackward0>)


In [6]:
model.layers[0].weight

Parameter containing:
tensor([[ 0.0505,  0.0585, -0.1843,  0.1082, -0.1442],
        [ 0.3844,  0.3576, -0.1766,  0.4423,  0.4139],
        [-0.2217, -0.1785, -0.0777,  0.4190, -0.2147]], requires_grad=True)

In [7]:
print(2)

2
